### ISSUE TITLE
Feature: do not select text after confirming selection

### ISSUE THREAD

**Issue by TommyX12** [wenhoujx/swiper#4]
Current behavior will select the searched text after confirming a selection. This is a little bit inconvenient. It would be great if there's a setting / option to turn it off.

By the way, great plugin! Exactly what I was looking for (coming from an Emacs background as well).

**Comment by wenhoujx** [comment]
hello, i am glad you liked it, GO EMACERS. 

would a configuration flag default to "true" - the select behavior, and one can turn it to `false` work for you? @TommyX12

**Comment by TommyX12** [comment]
Yep, that'd be perfect.

**Comment by wenhoujx** [comment]
[d0e290a](https://github.com/wenhoujx/swiper/commit/d0e290ae6b7e7b650e01952b6ea73700eb9b697e) provides this feature. 

I wrote a brief readme about configuration `swiper.selectMatch` .
