### ISSUE TITLE
Custom styling for match highlight?

### ISSUE THREAD

**Issue by ianyepan** [wenhoujx/swiper#5]
Thanks for this great extension! Is there any way to style the match highlight? On my machine the highlight boxes are too thick, covering up part of the words. Also would be nice to define custom color, and to accent the match of the current selected line to make it stand out from the rest of the matches.

**Comment by wenhoujx** [comment]
hello, i can take a look at this when i get back from my vacation may 15 :) . thanks for the feedback.

**Comment by wenhoujx** [comment]
don't have bandwidth on this, feel free to reopen if you want to make an contribution.
