### ISSUE TITLE
Matching algo suggestion

### ISSUE THREAD

**Issue by riotrah** [wenhoujx/swiper#8]
Thanks for this project. Surprisingly few of these out there, or at least they're hard to find. Great feature set etc. 

My use case is I've got a the following line in my file:

```clj
(defnc creatable-autocomplete
```

That I was hoping to be able to search for by swiping `c-a`. Based on my testing and reading of the source, the current algo wouldn't support this. Wondering if something like https://github.com/kentcdodds/match-sorter could be used here, optionally.

I can take a look at integrating this if you'd like, and you can decide how you'd prefer to expose the configuration.

> Small nit suggestion:
> Might I suggest making the title something like "swiper - fuzzy search buffer" or something, so that quickly groking my list of installed extensions is easier? Total first-world problem of course.

**Comment by wenhoujx** [comment]
on the small nit, i think the current description in `package.json` shows : "Emacs style swiper fuzzy search buffer/window", which will be matched against in the vscode extension search ?

**Comment by wenhoujx** [comment]
@riotrah  sorry not sure i get why you can't search that line: 
![image](https://github.com/wenhoujx/swiper/assets/4370201/f88324f2-f23c-426c-b81e-9d24fba690ba)

**Comment by riotrah** [comment]
Regarding naming:

Looks like looking for "swip" amongst my installed/enabled extensions _does_ find this, whereas looking for "fuzz" doesn't:

<img width="369" alt="Screenshot 2024-04-21 at 10 56 05 PM" src="https://github.com/wenhoujx/swiper/assets/22646419/d6e9b9f5-737b-4063-8ab6-8473b858ab72">

<img width="369" alt="Screenshot 2024-04-21 at 10 58 06 PM" src="https://github.com/wenhoujx/swiper/assets/22646419/7551e4c3-66f5-4a18-b9f9-0dbd63289a23">

**Comment by riotrah** [comment]
Regarding algo:

Yes, given the following line:

```clj
(defnc creatable-autocomplete
```

It's true that "swiping" with `(defnc creatable-auto` _does_ match. 

What I was hoping for, however, is being able to "swipe" with `c-a` instead, which does not _prefix_ or _substring_ match, but _does_ fuzzy match, at least according to `match-sorter`'s algo (per my testing it).

**Comment by wenhoujx** [comment]
oh you want fuzzy match, i often found fuzzy match not matching on things i want. For a code base with reasonable naming convention, i prefer to use substring match. 

to add fuzzy match would break other features such as regex match. 

i don't think i want to add this feature, hope you understand.
